'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.296
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PrintWorkshop.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property BookPlot() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("BookPlot", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Btn_AlignCentre() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Btn_AlignCentre", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Btn_AlignLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Btn_AlignLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Btn_AlignRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Btn_AlignRight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Btn_Delete() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Btn_Delete", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Btn_Edit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Btn_Edit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Btn_Frame() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Btn_Frame", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Btn_Inset() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Btn_Inset", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Btn_KeyFrame() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Btn_KeyFrame", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Btn_Label() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Btn_Label", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Btn_Labels() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Btn_Labels", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Btn_Legend() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Btn_Legend", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Btn_Opaque() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Btn_Opaque", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Btn_Place() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Btn_Place", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Btn_Reload() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Btn_Reload", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Btn_Scalebar() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Btn_Scalebar", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Btn_Scaletxt() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Btn_Scaletxt", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Btn_Table() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Btn_Table", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Btn_TextBold() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Btn_TextBold", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Btn_TextItalic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Btn_TextItalic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property Btn_Watermark() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Btn_Watermark", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Inset() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Inset", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property KeyFrameX() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("KeyFrameX", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Label() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Label", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property OverlayLegend() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("OverlayLegend", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property PlaceTemplate() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("PlaceTemplate", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property ScaleBar() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ScaleBar", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property ScaleText() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("ScaleText", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Table() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Table", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        Friend ReadOnly Property Watermark() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("Watermark", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
    End Module
End Namespace
